version: '3.6'
services:
  frontend:
    container_name: frontend-qsl-contacts
    build:
      context: .
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - "4200:4200"
