version: '3.6'
services:
  frontend:
    container_name: frontend-qsl-contacts
    build:
      context: .
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - "4200:4200"
      - '49153:49153'
    entrypoint: [ "ng", "serve", "--host", "0.0.0.0", "--poll", "2000" ]
