#########################
### build environment ###
#########################

# base image - latest LTS
FROM node:carbon as builder

# install chrome for protractor tests
# RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
# RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
# RUN apt-get update && apt-get install -yq google-chrome-stable

# set working directory
RUN mkdir /usr/src/app
WORKDIR /usr/src/app

# install and cache app dependencies
COPY package.json /usr/src/app/package.json
RUN npm install
RUN npm install -g @angular/cli@6.0.8 --unsafe

# add app
COPY . /usr/src/app

# run tests
# RUN ng test --watch=false

# generate build
RUN ng build --prod

##################
### production ###
##################

# base image
FROM nginx:1.15.1-alpine

# copy customized nginx.conf that contains reverse proxy setup for docker containers.
COPY ./nginx.conf /etc/nginx/nginx.conf
# copy artifact build from the 'build environment'
COPY --from=builder /usr/src/app/dist/frontend /usr/share/nginx/html

# Create directory necessary for creating/renewing the ssl cert.
RUN mkdir -p /usr/share/nginx/html/www/letsencrypt

# expose port 80 443
EXPOSE 80 443

# run nginx
CMD ["nginx", "-g", "daemon off;"]
