version: '3.6'
services:
  frontend:
    ports:
    - 4200:4200
    command:
      ng build
  backend:
    ports:
      - 3000:3000
  caddy:
    environment:
      #overwrite Caddy to localhost, which disables https.
      domain_1: "http://localhost:80"
      domain_2: "http://127.0.0.1:80"
