version: '3.6'
services:
  frontend:
    build:
      dockerfile: Dockerfile-prod
    ports:
      - '80:80'
      - '443:443'
    volumes:
      # This path depends on where the docker-compose file is being executed from and is only needed when creating/renewing the https ssl certs.
      # - /home/git/letsencrypt/well-known:/usr/share/nginx/html/www/letsencrypt
      # The created/renewed http ssl certs live here.
      - /etc/letsencrypt/:/etc/letsencrypt/
