version: '3.6'
services:
  frontend:
    command:
      ng build --prod
  caddy:
    volumes:
      #This is the offline location to store Caddy certificates in case the container is restarted.
      - $HOME/.caddy:/etc/caddycerts
    environment:
      domain_1: quartech.app
      domain_2: www.quartech.app
      CADDYPATH: /etc/caddycerts
